[server]
# Server host name
host = "127.0.0.1"
# Socket address to bind
ip = "[::]"
# Port that should be listened on
port = 8080
# Amount of worker threads
# If set to zero Triox will use one worker per physical CPU core
workers = 0
# REQUIRED:
# provide a random string for the following field
# secret = ""

# Disable sign_up service to prevent creation of new accounts through the API
registration = true

[files]
# Disable file system modification like uploading or moving files
read_only = false

[database]
# Database type (currently only MySQL is available)
type = "mysql"
# Username of the database user
user = "triox"
# Password of the database user
password = "triox"
# Database address
host = "localhost"
# Username of the database user
port = "3306"
# Name of the database
name = "triox"


[tls]
# Certificates can be easily created with certbot (https://certbot.eff.org/) by running
# certbot certonly --standalone
# Enable/disable TLS
enabled = false
# Path to the certificate file
certificate = "tls/cert.pem"
# Path to the key file
key = "tls/key.pem"
